from .odes import bacterial
from .odes import burgers_galerkin
from .odes import cubic_damped_SHO
from .odes import cubic_oscillator
from .odes import double_pendulum
from .odes import duffing
from .odes import enzyme
from .odes import hopf
from .odes import kinematic_commonroad
from .odes import linear_3D
from .odes import linear_2D
from .odes import linear_damped_SHO
from .odes import logistic_map
from .odes import logistic_map_control
from .odes import logistic_map_multicontrol
from .odes import lorenz
from .odes import lorenz_control
from .odes import lorenz_u
from .odes import lotka
from .odes import meanfield
from .odes import mhd
from .odes import oscillator
from .odes import pendulum
from .odes import pendulum_control
from .odes import pendulum_on_cart
from .odes import rossler
from .odes import van_der_pol
from .odes import yeast

from .simulation import simulate